# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/*'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'


    App\Command\InstallCommand:
        tags: ['console.command']

    App\Service\DatabaseConfigurator\DatabaseConfigurator:
        arguments:
            $logger: '@logger'
    database_connection:
        class: PDO
        factory: ['App\Service\DatabaseConfigurator\DatabaseConnectionFactory', 'createConnection']


    App\Service\DatabaseConfiguratorFilePath: ~
        # arguments:
            # $connectionsFilePath: '%kernel.project_dir%/path/to/connections.xml'
            

    App\Service\DatabaseConnection\DatabaseConnectionConfigurator:
        arguments:
            $systemInfoProvider: '@App\Service\SystemInfo\SystemInfoProvider'
            $xmlFileManager: '@App\Service\XmlFile\XmlFileManager'
            $logger: '@logger'
            $serverVersionProvider: '@App\Service\ServerVersion\ServerVersionProvider'
            $uuidGenerator: '@App\Utils\UuidGenerator'
            $userProvider: '@App\Service\SystemInfo\UserProvider'

    
    App\Service\XmlFile\XmlFileManager:
        arguments:
            $logger: '@logger'

    App\Service\ServerVersion\ServerVersionProvider:
        arguments:
            $logger: '@logger'

    App\Util\UuidGenerator: ~

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
